server:
  port:8081

spring:
  thymeleaf:
    prefix: classpath:/templates/
    #开发，不需要重启
    cache: false
    suffix: .html
    mode: HTML
    encoding: UTF-8
  web:
    resources:
      static-locations: classpath:/static/
